language: python

python:
  - "3.6.3"

sudo: required

services:
  - docker

# Roda Testes
script:
   - docker-compose -f docker-compose-test.yml up
   - coverage run --source=modelagem,analises,exportadores,importadores,radar_parlamentar manage.py test modelagem analises exportadores importadores radar_parlamentar

after_success:
  - coveralls
