language: python

sudo: required

python:
  - "3.6.3"

services:
  - docker

install:
  - pip install coveralls

script:
  - docker build -t radarparlamentar/test .
  - docker run -v $(pwd):/radar --rm radarparlamentar/test test
  - docker run -v $(pwd):/radar radarparlamentar/test coverage
  - coveralls
