version: "3.4"

services:

    django:
        build: .
        environment:
            - RADAR_CMD=test
            - CC_TEST_REPORTER_ID=${CC_TEST_REPORTER_ID}
            - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
            - RADAR_TEST="True"
        volumes:
            - .:/radar
