# EXAMPLE AT: https://github.com/nevercaution/docker-django-uwsgi-nginx
version: "3.1"

volumes:
    volume_radar_pg_data:
    volume_django_static:

services:

  postgres:
    image: postgres:10.2-alpine
    environment:
        - POSTGRES_USER=radar
        - POSTGRES_PASSWORD=${RADAR_DB_PASSWORD}
        - POSTGRES_DB=radar
          #    volumes:
          # - "volume_radar_pg_data:/var/lib/postgresql/data/pgdata"

  nginx:
    image: nginx:1.13.9-alpine
    volumes:
        - volume_django_static:/radar/radar_parlamentar/static
        - ./radar.sock:/radar/radar.sock
        - ./deploy/uwsgi_params:/radar/deploy/uwsgi_params
        - ./deploy/radar.nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - django
    depends_on:
        - django
    ports:
        - "80:80"
        - "443:443"

  django:
    image: radarparlamentar
    build: .
    volumes:
        - .:/radar
        - volume_django_static:/radar/radar_parlamentar/static
    links:
        - postgres
    depends_on:
        - postgres
    command: >
        bash -c "python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        uwsgi --ini /radar/deploy/radar_uwsgi.ini"
